"""Hydrate the Modal Volume's `.tmp/applications/` from Google Drive.

Cloud-first pipeline_daily_maintenance can only re-stamp cover letter dates
for folders it can see on the Modal Volume. Folders generated by the legacy
local pipeline live on Drive but were never copied to the Volume — hydrating
once at the start of each daily run closes that gap.

Hydrate is best-effort: a high failure rate is logged but never blocks the
downstream re-stamp stage (which works on whatever made it onto the Volume).

Usage:
    python -m execution.hydrate_volume_from_drive --since-days 365
    python -m execution.hydrate_volume_from_drive --dry-run
    python -m execution.hydrate_volume_from_drive --max-workers 8
"""
from __future__ import annotations

import argparse
import logging
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timedelta, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from execution.drive_upload import (  # noqa: E402
    download_application_folder,
    list_application_folders,
)

logging.basicConfig(level=logging.INFO, format="%(message)s")
log = logging.getLogger(__name__)

ROOT = Path(__file__).resolve().parent.parent
APPS_DIR = ROOT / ".tmp" / "applications"


def _local_job_ids(local_root: Path) -> set[str]:
    if not local_root.exists():
        return set()
    ids: set[str] = set()
    for folder in local_root.iterdir():
        if folder.is_dir() and folder.name.startswith("J-"):
            ids.add(folder.name.split("_")[0])
    return ids


def _parse_modified(ts: str | None) -> datetime | None:
    if not ts:
        return None
    try:
        return datetime.fromisoformat(ts.replace("Z", "+00:00"))
    except ValueError:
        return None


def _sweep_stale_parts(local_root: Path, age_hours: int = 24) -> int:
    """Remove orphaned `.part` files older than `age_hours`.

    `.part` files are created by `download_application_folder` and renamed in
    place on success. Anything older than 24h is from a crashed run.
    """
    if not local_root.exists():
        return 0
    cutoff_ts = time.time() - age_hours * 3600
    removed = 0
    for part in local_root.rglob("*.part"):
        try:
            if part.stat().st_mtime < cutoff_ts:
                part.unlink()
                removed += 1
        except OSError:
            pass
    if removed:
        log.info(f"[hygiene] swept {removed} stale .part files (older than {age_hours}h)")
    return removed


def _download_one(f: dict, local_root: Path) -> tuple[str, bool, str]:
    """Worker for the thread pool. Returns (folder_name, ok, error_message)."""
    name = f["name"]
    try:
        result = download_application_folder(name, local_root)
        if result is None:
            return (name, False, "not found on Drive")
        return (name, True, "")
    except Exception as exc:
        log.warning(f"[fail] {name}: {exc}")
        return (name, False, str(exc))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--local-root", default=str(APPS_DIR))
    parser.add_argument(
        "--since-days",
        type=int,
        default=365,
        help="Only hydrate Drive folders modified in the last N days (default 365).",
    )
    parser.add_argument("--limit", type=int, default=0, help="Stop after N downloads (debug).")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument(
        "--max-workers",
        type=int,
        default=8,
        help="Concurrent download threads (default 8).",
    )
    parser.add_argument(
        "--stale-hours",
        type=int,
        default=24,
        help="Sweep .part files older than N hours at startup (default 24).",
    )
    args = parser.parse_args()

    local_root = Path(args.local_root)
    local_root.mkdir(parents=True, exist_ok=True)

    _sweep_stale_parts(local_root, age_hours=args.stale_hours)

    log.info("Listing Drive J-* folders under DOE Applications/ ...")
    drive_folders = list_application_folders()
    log.info(f"Drive folders found: {len(drive_folders)}")

    cutoff = datetime.now(timezone.utc) - timedelta(days=args.since_days)
    local_ids = _local_job_ids(local_root)
    log.info(f"Local Volume already has: {len(local_ids)} J-* folders")

    missing: list[dict] = []
    too_old = 0
    for f in drive_folders:
        job_id = f["name"].split("_")[0]
        if job_id in local_ids:
            continue
        modified = _parse_modified(f.get("modifiedTime"))
        # NOTE: if modified is None, fall through and include the folder.
        # A missing/unparseable timestamp shouldn't silently exclude it from hydration.
        if modified is not None and modified < cutoff:
            too_old += 1
            continue
        missing.append(f)

    log.info(
        f"Missing locally: {len(missing)} | filtered (older than {args.since_days}d): {too_old}"
    )

    if args.dry_run:
        for f in missing[: args.limit or 25]:
            log.info(f"[dry-run] would fetch: {f['name']} (modified {f.get('modifiedTime')})")
        log.info(f"[dry-run] total missing: {len(missing)}")
        return

    if args.limit:
        missing = missing[: args.limit]

    fetched = 0
    failed: list[tuple[str, str]] = []
    workers = max(1, args.max_workers)

    with ThreadPoolExecutor(max_workers=workers) as pool:
        futures = [pool.submit(_download_one, f, local_root) for f in missing]
        for i, fut in enumerate(as_completed(futures), 1):
            name, ok, err = fut.result()
            if ok:
                fetched += 1
            else:
                failed.append((name, err))
            if i % 50 == 0:
                log.info(
                    f"Progress: {i}/{len(missing)} (fetched={fetched}, failed={len(failed)})"
                )

    log.info("")
    log.info(f"Done. fetched={fetched}, failed={len(failed)}, candidates={len(missing)}")
    if failed:
        log.info("First 10 failures:")
        for name, msg in failed[:10]:
            log.info(f"  {name}: {msg}")
        # Hydrate is best-effort. A high failure rate is logged loudly but does
        # NOT exit non-zero — the downstream re-stamp stage must still run on
        # whatever folders did make it onto the Volume.
        fail_rate = len(failed) / max(len(missing), 1)
        if fail_rate > 0.20:
            log.error(
                f"Hydrate failure rate {fail_rate:.0%} exceeds 20% threshold — "
                f"continuing anyway, re-stamp will run on whatever is on Volume"
            )


if __name__ == "__main__":
    main()
